### ISSUE TITLE
Usage scenarios

### ISSUE THREAD

**Issue by gedw99** [qrtz/nativemessaging#1]
This might help me with desktop and mobile apps.
Would you mind thinking about this because rough RPC between web UI and golang is pretty awful at the moment.

You library looks very well done so maybe it can help with the 2 following use cases ?

On desktop I am using gallium which is similar to Electron but built in golang with the chromium engine embedded.
https://github.com/alexflint/gallium

On mobile I use gomobile and start up a webview to run the web UI.i am curious if this will work too

**Comment by qrtz** [comment]
Thank you for your feedback.
This library is useful when your go code need to interact with an external application that implements the [Native Messaging Protocol](https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-protocol)
However I don't think this library would be useful in these particular scenarios
